baseURL = "https://hackandsnack.de/"
title = "Hack 'n' Snack"
DefaultContentLanguage = "de"
theme = "beautifulhugo"

[Params]
    subtitle = "Jeden letzten Dienstag im Monat ab 18 Uhr im PING!"
    logo = "img/avatar-icon.png"
    favicon = "img/favicon.ico"
    dateFormat = "02.01.2006"
    commit = false
    rss = true
    comments = true

[[Params.bigimg]]
    src = "img/sphere.jpg"

[Author]
    name = "FOSS-AG"
    website = "https://foss-ag.de"
    email = "info@hackandsnack.de"
    github = "foss-ag"
    telegram = "FOSSAG"
    twitter = "fossagtudo"

[[menu.main]]
    name = "Archive"
    url = "https://cloud.foss-ag.de/index.php/s/ZcH44yNA3DEXkBp?path=%2FHack%20and%20Snack"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Über uns"
    url = "page/about/"
    weight = 3
